name: 'Terraform'

on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_KEY_ID: ${{ secrets.SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.9
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: format

    - name: Terraform validate
      run: validate

    - name: Terraform Plan
      run: plan #-input=false

    #- name: Terraform Apply
    #  run: terraform apply #-auto-approve -input=false
